FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /src
COPY . .
RUN mvn -pl rover-nameserver-bootstrap -am -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /src/rover-nameserver-bootstrap/target/rover-nameserver-bootstrap-1.0.0-SNAPSHOT.jar app.jar
COPY deploy/docker/config/rover-nameserver.yml config/rover-nameserver.yml
EXPOSE 8888 8889
ENTRYPOINT ["java", "-jar", "app.jar"]
